### PR TITLE
Using ElementTree to create XML

### PR DESCRIPTION
**Pull request by Tan0**
Support using ElementTree to create XML dynamically.
This is a first step. Replace get_request() and
power_state_request(), rest of functions are easy to extend.

### CODE REVIEW

**Comment by Tan0** [comment]
hmmm, looks like `client` can't pass py34

**Comment by sdague** [comment]
Can you be more specific about what kind of extending you are planning. I personally find reading the document to be a ton easier than creating the XML dynamically. It's also easier to compare against standards. I'd much rather just add the dynamism that's actually needed here, not prematurely abstract things.

**Comment by Tan0** [comment]
Currently, hard code XML is good enough for AMT library. But create XML dynamically is easy to follow AMT Implementation and Reference Guide to extend other features.

For example,enable_remote_kvm could simply follow this guide, get kvmRedirectionSettingDataRef first and change its values properly:

$kvmRedirectionSettingDataRef =$wsmanConnectionObject.NewReference("SELECT \* FROM IPS_KVMRedirectionSettingData WHERE InstanceID='Intel(r) KVM Redirection Settings'")
$kvmRedirectionSettingDataInstance =$kvmRedirectionSettingDataRef.Get()
$kvmRedirectionSettingDataInstance.SetProperty("Is5900PortEnabled","true")
$kvmRedirectionSettingDataInstance.SetProperty("RFBPassword","P@ssw0rd")
$kvmRedirectionSettingDataRef.Put($kvmRedirectionSettingDataInstance)

**Comment by sdague** [comment]
Right, honestly, I feel like that doesn't make this easier to understand or use. It was that kind of thing that made me rewrite this in the first place. 

I can understand your desire to do something more like that, but I feel like the simple hard coded version is easier to understand for people that don't think in xml.

**Pull request closed without merging**
